#!/bin/bash

xray_script="./xray.sh"

echo "Populating configs dropdown"
configs=$(find ~ /opt -type f -name "*.json" ! -path "*/Library/*" -exec grep -l '"inbounds"' {} + | while read -r config; do grep -A 5 '"vnext"' "$config" | grep '"address"' | awk '{print $2}' | tr -d ',"' | xargs -I {} echo "{\"title\": \"{}\", \"value\": \"$config\"}"; done | paste -sd ',' -)
arg1="# @raycast.argument1 {\"type\": \"dropdown\", \"placeholder\": \"config\", \"data\": [{\"title\": \"Setup\", \"value\": \"setup\"},${configs}]}"
sed -i '' "/# @raycast.argument1/c\\
$arg1
" "$xray_script"

echo "Populating apps dropdown"
apps=$(find /Applications -type d -name "*.app" ! -path "*/Contents/*" | while read -r app; do basename "$app" .app; done | sort | awk '{print "{\"title\": \"" $0 "\", \"value\": \"" $0 "\"}"}' | paste -sd ',' -)
arg2="# @raycast.argument2 {\"type\": \"dropdown\", \"placeholder\": \"app\", \"data\": [{\"title\": \"System\", \"value\": \"system\"},${apps}]}"
sed -i '' "/# @raycast.argument2/c\\
$arg2
" "$xray_script"

echo "Populating ifaces dropdown"
ifaces=$(networksetup -listallnetworkservices | sed '1d' | awk '{print "{\"title\": \"" $0 "\", \"value\": \"" $0 "\"}"}' | paste -sd ',' -)
arg3="# @raycast.argument3 {\"type\": \"dropdown\", \"placeholder\": \"interface\", \"data\": [${ifaces}]}"
sed -i '' "/# @raycast.argument3/c\\
$arg3
" "$xray_script"
echo "Done."